#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  scale)
    if [[ -z $2 ]]; then
      echo "Please specify an app to scale"
      exit 1
    fi
    APP="$2"
    REPO="$DOKKU_ROOT/$APP"
    if [ ! -d "$REPO" ]; then
      echo "No matching app: $APP"
      exit 1
    fi
    shift
    shift
    SCALEFILE="$REPO/SCALE"
    for line in "$@"
    do
      echo "$line"
    done > "$SCALEFILE"
    echo "Scaling app $APP:"
    cat -n "$REPO/SCALE"     
    REF=$(cat $REPO/refs/heads/master)
    cd $REPO && git archive $REF | dokku receive $APP | sed -u "s/^/"$'\e[1G'"/"
    ;;
  help)
    cat && cat<<EOF
    scale <app> TYPE1=NUM1 [TYPE2=NUM2 ...]         Scale an app
EOF
  ;;

esac
