#!/bin/bash
APP="$1"
IMAGE="app/$1"
SCALE_FILE="$DOKKU_ROOT/$APP/SCALE"

set -e

# Copies a file from the host into the container
function copy_to_container() {
  SOURCE_FILE="$1"
  TARGET_FILE="$2"
  if [ ! -f "$SOURCE_FILE" ]; then
    echo "Source file does not exist on host: $SOURCE_FILE"
    exit 1
  fi
  id=$(cat "$SOURCE_FILE" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > '$TARGET_FILE'")
  docker attach $id
  test $(docker wait $id) -eq 0
  docker commit $id $IMAGE > /dev/null
}

PLUGIN_DIR=$(dirname $0)
copy_to_container "$PLUGIN_DIR/lib/procfile-to-supervisord" /build/procfile-to-supervisord
if [ -f "$SCALE_FILE" ]; then
  echo "Found SCALE file: $SCALE_FILE"
  copy_to_container "$SCALE_FILE" /app/.profile.d/SCALE
else
  echo "No SCALE file found; will use default of one process per entry in Procfile."
fi

echo "-----> Injecting Logging Supervisor ..."
id=$(cat "$PLUGIN_DIR/lib/runner" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /start && apt-get update && apt-get install -y supervisor && apt-get clean")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
