#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$2"

if [[ -z $APP ]]; then
    cat <<EOF
dokku-cfg-logrotate <create|remode> <app>
create     Create logrotate config for app if not exists.
remove     Remove logrotate config if not changed by user.
EOF
    exit 1;
fi

# TODO: Maybe need strart some prerotate postrotate script inside docker running container?
function create_log_rotate() {
  APP="$1"
  LOGROT_FILE="$2"
  if [ ! -f "$LOGROT_FILE" ]; then
    echo "       Creating $LOGROT_FILE"
    cat >> "$LOGROT_FILE" <<EOF
"/var/log/dokku/$APP/*log" {
  weekly
  su root
  missingok
  rotate 52
  compress
  sharedscripts
}
EOF
  fi
}

case "$1" in
    create)
        LOGROT_FILE="/etc/logrotate.d/dokku-app.d/$APP"
        create_log_rotate "$APP" "$LOGROT_FILE"
        chown root:root "$LOGROT_FILE"
        chmod 644 "$LOGROT_FILE"
        ;;
esac
