#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$2"
CHECKSUM_FILE="$3"
LOGROT_FILE="/etc/logrotate.d/dokku-app.d/$APP"

if [[ -z $APP || -z $CHECKSUM_FILE ]]; then
    cat <<EOF
dokku-cfg-logrotate <create|remode> <app> <checksumfilename>
create     Create logrotate config for app if not exists.
remove     Remove logrotate config if not changed by user.
EOF
    exit 1;
fi

# TODO: Maybe need strart some prerotate postrotate script inside docker running container?
function create_log_rotate() {
  APP="$1"
  LOGROT_FILE="$2"
  if [ ! -f "$LOGROT_FILE" ]; then
    echo "       Creating $LOGROT_FILE"
    cat > "$LOGROT_FILE" <<EOF
"/var/log/dokku/$APP/*log" {
  weekly
  su root
  missingok
  rotate 52
  compress
  sharedscripts
}
EOF
  fi
}

case "$1" in
    create)
        create_log_rotate "$APP" "$LOGROT_FILE"
        chown root:root "$LOGROT_FILE"
        chmod 644 "$LOGROT_FILE"

        md5sum "$LOGROT_FILE" > "$CHECKSUM_FILE"
        ;;
    remove)
        if [[ -f "$CHECKSUM_FILE" && -f "$LOGROT_FILE" ]]; then
            savedMD5=$(cat "$CHECKSUM_FILE")
            currentMD5=$(md5sum "$LOGROT_FILE")
            if [[ "$currentMD5" = "$savedMD5" ]]; then
                rm "$LOGROT_FILE"
                else
                echo "       Keep user changed logrotate file $LOGROT_FILE"
            fi
        fi
        ;;
esac
