#!/bin/bash

set -e
export HOME=/app
hash -r
cd $HOME

# Generate supervisord.conf:
bash /build/procfile-to-supervisord /app/Procfile /app/SCALE > supervisord.conf

# Create /var/log/app directory
mkdir -p /var/log/app

# Get buildstep user if it exists and chown log dir
user_name=$(egrep "^u[1-9]+" /etc/passwd 2> /dev/null | awk -F':' '{ print $1 }')
[[ -n "$user_name" ]] && chown -R $user_name /var/log/app

# Display the generated supervisord.conf:
echo "Generated supervisord.conf:"
cat -n supervisord.conf

# Start up the app:
supervisord -c supervisord.conf
