#!/bin/bash

set -e
export HOME=/app
hash -r
cd $HOME

# source in app env for things like DOKKU_SUPERVISOR_RUN
if [[ -d /app/.profile.d ]]; then
  for file in /app/.profile.d/*.sh; do
    source $file
  done
fi
# need to unset PYTHON vars to use apt installed supervisord
unset PYTHONHOME
unset PYTHONPATH

# Generate supervisord.conf:
bash /usr/local/bin/procfile-to-supervisord /app/Procfile /app/SCALE > supervisord.conf

# Create /var/log/app directory
mkdir -p /var/log/app

# Get buildstep user if it exists and chown log dir
user_name=$(stat -c %U /app)
user_group=$(stat -c %G /app)
mount_list="/var/log/app /mnt/whoosh_index /mnt/simsrv"
if [[ -n "$user_name" ]] && [[ -n "$user_group" ]];then
    for mount in $mount_list; do
        if [ -d "$mount" ];then
            chown -R ${user_name}:${user_group} "$mount"
            chmod -R g+rw "$mount"
        fi
    done
fi

# Display the generated supervisord.conf:
echo "Generated supervisord.conf:"
cat -n supervisord.conf

# Start up the app:
exec supervisord -c supervisord.conf
