#!/bin/bash

set -e
export HOME=/app
hash -r
cd $HOME

# source in app env for things like DOKKU_SUPERVISOR_RUN
if [[ -d /app/.profile.d ]]; then
  for file in /app/.profile.d/*.sh; do
    source $file
  done
fi
# need to unset PYTHON vars to use apt installed supervisord
unset PYTHONHOME
unset PYTHONPATH

# Generate supervisord.conf:
bash /usr/local/bin/procfile-to-supervisord /app/Procfile /app/SCALE > supervisord.conf

# Create /var/log/app directory
mkdir -p /var/log/app

# Change ownership of /var/log/app to non-root container user
APP_USER=$(stat -c %U /app)
APP_GROUP=$(stat -c %G /app)
mount_list="/var/log/app /mnt/whoosh_index /mnt/simsrv"
if [[ -n "$APP_USER" ]] && [[ -n "$APP_GROUP" ]]; then
  for mount in $mount_list; do
    if [[ -d "$mount" ]];then
      chown -R "${APP_USER}:${APP_GROUP}" "$mount"
      chmod -R g+rw "$mount"
    fi
  done
fi

# Display the generated supervisord.conf:
echo "Generated supervisord.conf:"
cat -n supervisord.conf

# Start up the app:
exec supervisord -c supervisord.conf
